language: csharp
solution: BossFight.sln

addons:
  apt:
    packages:
    - nuget

mono: none
dotnet: 5.0

install:
  - nuget restore BossFight.sln
  - dotnet add ./BossFight.Tests/BossFight.Tests.csproj package NUnit.Console --version 3.12.0 --package-directory testrunner

script:
  - dotnet build /p:Configuration=Release BossFight.sln
  - dotnet test