language: csharp
solution: MysticHorizonsLib.sln

addons:
  apt:
    packages:
    - nuget

mono: none
dotnet: 5.0

install:
  - nuget restore MysticHorizonsLib.sln
  - dotnet add ./MysticHorizonsLib.Tests/MysticHorizonsLib.Tests.csproj package NUnit.Console --version 3.12.0 --package-directory testrunner

script:
  - dotnet build /p:Configuration=Release MysticHorizonsLib.sln
  - dotnet test