language: csharp
solution: Bossfight.sln
addons:
  apt:
    packages:
    - nuget
install:
  - nuget restore Bossfight.sln
  - nuget install NUnit.Console -Version 2.8.7 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Bossfight.sln
  - mono ./testrunner/NUnit.ConsoleRunner.2.8.7/tools/nunit3-console.exe ./TestBossFight/bin/Release/TestBossFight.dll