language: csharp
solution: Bossfight.sln

addons:
  apt:
    packages:
    - nuget

mono: none
dotnet: 5.0

install:
  - nuget restore Bossfight.sln
  #- nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
  - dotnet add ./TestBossFight/TestBossFight.csproj package NUnit.Console --version 3.12.0 --package-directory testrunner

script:
  - msbuild /p:Configuration=Release Bossfight.sln
  - dotnet ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./TestBossFight/bin/Release/TestBossFight.dll